services:
  postgres:
    image: postgres:16-alpine
    container_name: cs308-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - cs308_pg_data:/var/lib/postgresql/data

volumes:
  cs308_pg_data:
